namespace: bookstore
environment: Production
replicaCount: 1

service:
  name: inventoryservice
  port: 80

image:
  repository: bookstoreaurega.azurecr.io/inventoryservice
  tag: latest
  pullPolicy: Always

ingress:
  host: ""
  path: /inventory

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
