apiVersion: v2
name: notificationservice
description: BookStore Notification Service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: bookstore-lib
    version: "0.1.0"
    repository: "file://../bookstore-lib"
