trigger: none  # Manual trigger only for releases

variables:
  azureSubscription: 'AzureServiceConnectionName'
  productServiceApp: 'bookstore-product-service'
  inventoryServiceApp: 'bookstore-inventory-service'
  productUiApp: 'bookstore-product-ui'

stages:
- stage: Release
  displayName: 'Deploy to Azure App Services'
  jobs:
  - job: DeployProductService
    displayName: 'Deploy ProductService'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download ProductService Artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'ProductService'
        downloadPath: '$(Pipeline.Workspace)/drop'
    
    - script: ls -R $(Pipeline.Workspace)/drop/ProductService
      displayName: 'Verify ProductService Artifact Contents'
      
    - task: AzureWebApp@1
      displayName: 'Deploy ProductService'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(productServiceApp)'
        package: '$(Pipeline.Workspace)/drop/ProductService/BookStore.ProductService.API.zip'

  - job: DeployInventoryService
    displayName: 'Deploy InventoryService'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy InventoryService'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(inventoryServiceApp)'
        package: '$(Pipeline.Workspace)/drop/InventoryService/InventoryService.API.zip'

  - job: DeployAngularApp
    displayName: 'Deploy Angular UI'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy Angular App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(productUiApp)'
        package: '$(Pipeline.Workspace)/drop/ProductUI'