trigger: none  # Manual trigger only

# 🔄 Reference the build pipeline to select artifacts at runtime
resources:
  pipelines:
  - pipeline: buildPipeline
    source: ankitgoelmalviyans.BookStore                # Name of the build pipeline
    project: BookStore               # Azure DevOps project name
    trigger: none                    # Disable automatic triggers

variables:
  azureSubscription: 'AzureServiceConnectionName'
  productServiceApp: 'bookstore-product-service'
  inventoryServiceApp: 'bookstore-inventory-service'
  productUiApp: 'bookstore-product-ui'

stages:
- stage: Release
  displayName: 'Deploy to Azure App Services'
  jobs:

  # ----------------- ProductService -------------------
  - job: DeployProductService
    displayName: 'Deploy ProductService'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: buildPipeline
      artifact: ProductService

    - task: AzureWebApp@1
      displayName: 'Deploy ProductService'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(productServiceApp)'
        package: '$(Pipeline.Workspace)/buildPipeline/ProductService/BookStore.ProductService.API.zip'


  # ----------------- InventoryService -------------------
  - job: DeployInventoryService
    displayName: 'Deploy InventoryService'
    dependsOn: DeployProductService
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: buildPipeline
      artifact: InventoryService

    - task: AzureWebApp@1
      displayName: 'Deploy InventoryService'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(inventoryServiceApp)'
        package: '$(Pipeline.Workspace)/buildPipeline/InventoryService/InventoryService.API.zip'


  # ----------------- ProductUI (Angular) -------------------
  - job: DeployAngularApp
    displayName: 'Deploy Angular UI'
    dependsOn: DeployInventoryService
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: buildPipeline
      artifact: ProductUI

    - task: AzureWebApp@1
      displayName: 'Deploy Angular App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(productUiApp)'
        package: '$(Pipeline.Workspace)/buildPipeline/ProductUI'
