# trigger:
#   branches:
#     include:
#       - main
trigger: none 
variables:
- group: BookStoreSecrets
- name: azureSubscription
  value: 'AzureServiceConnectionName'
- name: resourceGroup
  value: 'BookStoreRG'
- name: location
  value: 'East US'
- name: productServiceApp
  value: 'bookstore-product-service'
- name: inventoryServiceApp
  value: 'bookstore-inventory-service'
- name: productUiApp
  value: 'bookstore-product-ui'
- name: serviceBusNamespace
  value: 'bookstore-servicebus'
- name: topicName
  value: 'product-events'
- name: subscriptionName
  value:
