trigger: none  # Manual trigger only for releases

resources:
  pipelines:
  - pipeline: buildPipeline
    source: ankitgoelmalviyans.BookStore    # Your build pipeline name
    project: BookStore                      # Your Azure DevOps project name
    trigger: none

variables:
  azureSubscription: 'AzureServiceConnectionName'
  productServiceApp: 'bookstore-product-service'
  inventoryServiceApp: 'bookstore-inventory-service'
  productUiApp: 'bookstore-product-ui'

stages:
- stage: Release
  displayName: 'Deploy to Azure App Services'
  jobs:

  # ----------------- ProductService -------------------
  - job: DeployProductService
    displayName: 'Deploy ProductService'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: buildPipeline
      artifact: drop

    - task: AzureWebApp@1
      displayName: 'Deploy ProductService'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(productServiceApp)'
        package: '$(Pipeline.Workspace)/buildPipeline/drop/ProductService/BookStore.ProductService.API.zip'

  # ----------------- InventoryService -------------------
  - job: DeployInventoryService
    displayName: 'Deploy InventoryService'
    dependsOn: DeployProductService
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: buildPipeline
      artifact: drop

    - task: AzureWebApp@1
      displayName: 'Deploy InventoryService'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(inventoryServiceApp)'
        package: '$(Pipeline.Workspace)/buildPipeline/drop/InventoryService/InventoryService.API.zip'

  # ----------------- Angular Product-UI -------------------
  - job: DeployAngularUI
    displayName: 'Deploy Angular Product UI'
    dependsOn: DeployInventoryService
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: buildPipeline
      artifact: drop

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy Angular UI to WebApp'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(azureSubscription)'
        appType: 'webAppLinux'
        WebAppName: '$(productUiApp)'
        packageForLinux: '$(Pipeline.Workspace)/buildPipeline/drop/ProductUI'
