trigger: none  # Manual trigger only for releases

variables:
  azureSubscription: 'AzureServiceConnectionName'
  productServiceApp: 'bookstore-product-service'
  inventoryServiceApp: 'bookstore-inventory-service'
  productUiApp: 'bookstore-product-ui'

stages:
- stage: Release
  displayName: 'Deploy to Azure App Services'
  jobs:
  - job: DeployProductService
    displayName: 'Deploy ProductService'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy ProductService'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(productServiceApp)'
        package: '$(Pipeline.Workspace)/drop/ProductService'

  - job: DeployInventoryService
    displayName: 'Deploy InventoryService'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy InventoryService'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(inventoryServiceApp)'
        package: '$(Pipeline.Workspace)/drop/InventoryService'

  - job: DeployAngularApp
    displayName: 'Deploy Angular UI'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy Angular App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(productUiApp)'
        package: '$(Pipeline.Workspace)/drop/ProductUI'
