trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: BookStoreSecrets

steps:
- script: |
    echo "JwtKey: $(JwtKey)"
    echo "KafkaBootstrapServers: $(KafkaBootstrapServers)"
    echo "KafkaUsername: $(KafkaUsername)"
    echo "KafkaPassword: $(KafkaPassword)"
    echo "CosmosEndpoint: $(CosmosEndpoint)"
    echo "CosmosKey: $(CosmosKey)"
  displayName: 'Print Secret Variables (test)'
