trigger: none

variables:
- group: BookStoreSecrets
- name: azureSubscription
  value: 'AzureServiceConnectionName'
- name: aksClusterName
  value: 'bookstore-aks'
- name: aksResourceGroup
  value: 'BookStoreRG'
- name: namespace
  value: 'bookstore'
- name: imageRepository
  value: 'productservice'
- name: imageRepositoryInventory
  value: 'inventoryservice'
- name: containerRegistry
  value: 'bookstoreaure.azurecr.io'
- name: imageTag
  value: 98
- name: apimResourceGroup
  value: 'BookStoreRG'
- name: apimInstance
  value: 'bookstore-apim-new-1'

stages:
- stage: Deploy
  displayName: 'Deploy Services to AKS'
  jobs:
  - job: DeployToKubernetes
    displayName: 'Deploy ProductService and InventoryService'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Create Secrets, Deploy Services, and Create Ingress'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite-existing
          kubectl get namespace $(namespace) || kubectl create namespace $(namespace)

          echo "Creating productservice secrets..."
          kubectl create secret generic productservice-secrets \
            --from-literal=Jwt__Key="$(JwtKey)" \
            --from-literal=Kafka__BootstrapServers="$(KafkaBootstrapServers)" \
            --from-literal=Kafka__Username="$(KafkaUsername)" \
            --from-literal=Kafka__Password="$(KafkaPassword)" \
            --from-literal=Cosmos__Endpoint="$(CosmosEndpoint)" \
            --from-literal=Cosmos__Key="$(CosmosKey)" \
            --from-literal=ServiceBus__Connection="$(ServiceBusConnection)" \
            --namespace="$(namespace)" --dry-run=client -o yaml | kubectl apply -f -

          echo "Creating inventoryservice secrets..."
          kubectl create secret generic inventoryservice-secrets \
            --from-literal=Jwt__Key="$(JwtKey)" \
            --from-literal=Kafka__KafkaBootstrapServers="$(KafkaBootstrapServers)" \
            --from-literal=Kafka__KafkaUsername="$(KafkaUsername)" \
            --from-literal=Kafka__KafkaPassword="$(KafkaPassword)" \
            --from-literal=Cosmos__Endpoint="$(CosmosEndpoint)" \
            --from-literal=Cosmos__Key="$(CosmosKey)" \
            --from-literal=ServiceBus__Connection="$(ServiceBusConnection)" \
            --namespace="$(namespace)" --dry-run=client -o yaml | kubectl apply -f -

          echo "Deploying ProductService and InventoryService..."
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: productservice
            namespace: $(namespace)
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: productservice
            template:
              metadata:
                labels:
                  app: productservice
              spec:
                containers:
                - name: productservice
                  image: $(containerRegistry)/$(imageRepository):$(imageTag)
                  ports:
                  - containerPort: 80
                  env:
                  - name: ASPNETCORE_URLS
                    value: http://+:80
                  envFrom:
                  - secretRef:
                      name: productservice-secrets
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: productservice
            namespace: $(namespace)
          spec:
            selector:
              app: productservice
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: inventoryservice
            namespace: $(namespace)
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: inventoryservice
            template:
              metadata:
                labels:
                  app: inventoryservice
              spec:
                containers:
                - name: inventoryservice
                  image: $(containerRegistry)/$(imageRepositoryInventory):$(imageTag)
                  ports:
                  - containerPort: 80
                  env:
                  - name: ASPNETCORE_URLS
                    value: http://+:80
                  envFrom:
                  - secretRef:
                      name: inventoryservice-secrets
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: inventoryservice
            namespace: $(namespace)
          spec:
            selector:
              app: inventoryservice
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP
          EOF

          echo "Creating Ingress for productservice and inventoryservice..."
          cat <<EOF | kubectl apply -f -
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: bookstore-ingress
            namespace: $(namespace)
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          spec:
            tls:
            - hosts:
              - $(productHost)
              - $(inventoryHost)
              secretName: bookstore-tls
            rules:
            - host: $(productHost)
              http:
                paths:
                - path: /swagger
                  pathType: Prefix
                  backend:
                    service:
                      name: productservice
                      port:
                        number: 80
                - path: /api
                  pathType: Prefix
                  backend:
                    service:
                      name: productservice
                      port:
                        number: 80
            - host: $(inventoryHost)
              http:
                paths:
                - path: /swagger
                  pathType: Prefix
                  backend:
                    service:
                      name: inventoryservice
                      port:
                        number: 80
                - path: /api
                  pathType: Prefix
                  backend:
                    service:
                      name: inventoryservice
                      port:
                        number: 80
          EOF

- stage: ImportToAPIM
  displayName: 'Import APIs to APIM'
  dependsOn: Deploy
  condition: succeeded()
  jobs:
  - job: ImportAPI
    displayName: 'Import Swagger to APIM and Set serviceUrl'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Import Product & Inventory APIs'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite-existing

          PRODUCT_DNS="$(productHost)"
          INVENTORY_DNS="$(inventoryHost)"

          echo "Importing ProductService API..."
          az apim api import \
            --resource-group $(apimResourceGroup) \
            --service-name $(apimInstance) \
            --api-id productservice-api \
            --path product \
            --display-name "ProductService API" \
            --specification-url "https://${PRODUCT_DNS}/swagger/v1/swagger.json" \
            --specification-format OpenApi

          az apim api update \
            --resource-group $(apimResourceGroup) \
            --service-name $(apimInstance) \
            --api-id productservice-api \
            --set serviceUrl=https://${PRODUCT_DNS}

          echo "Importing InventoryService API..."
          az apim api import \
            --resource-group $(apimResourceGroup) \
            --service-name $(apimInstance) \
            --api-id inventoryservice-api \
            --path inventory \
            --display-name "InventoryService API" \
            --specification-url "https://${INVENTORY_DNS}/swagger/v1/swagger.json" \
            --specification-format OpenApi

          az apim api update \
            --resource-group $(apimResourceGroup) \
            --service-name $(apimInstance) \
            --api-id inventoryservice-api \
            --set serviceUrl=https://${INVENTORY_DNS}
